package com.aluracursos.backend.domain.user;

// Asegúrate de importar la clase para tu lista, por ejemplo:
// import com.aluracursos.backend.domain.role.Role;

import org.springframework.stereotype.Component;
import java.util.Set;

@Component
public class UserMapper {

    public User mapToEntity(UserForm form, String hashedPassword) {
        return new User(
                null, // The ID is auto-generated by the database
                form.name(),
                form.email(),
                hashedPassword,

                Set.of(Profile.ROLE_USER)
        );
    }
}
